# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: en-US
title: Dagware
email: feedback@dagwarer.com
description: >- # this means to ignore newlines until "baseurl:"
  Dagware
logo: /assets/icons/logo48.png
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dagware.github.io" # the base hostname & prtotocol for your site, e.g. http://example.com
#disqus:
#    shortname: thenewbiewoodworker
author:
  name: Dan Thomas
  picture: /assets/images/me.jpg
#instagram_username: thenewbiewoodworker
#youtube_username: thenewbiewoodworker
# search: true
# search_full_content: true

# Build settings
markdown: kramdown
plugins: # previously gems
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
##  - jekyll-feed
#  - jekyll-redirect-from

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 20
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
#  - /videos/_template.md
#  - /products/_template.md

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true